### ISSUE TITLE
SshService is empty

### ISSUE THREAD

**Issue by sajjadintel** [Anton2319/VPNoverSSH#1]
hi
Could you update your code?
It seems it's not working.
Thanks.

**Comment by Anton2319** [comment]
I had no time to work on my project for the past 2 weeks. Gonna continue very soon, so put a watch on a repo 🤗💜

**Comment by Anton2319** [comment]
For now if you want it working you gotta use the app called termux. Launch an ssh connection with these parameters: `ssh username@host -L 1080` and then press "Toggle" button

**Comment by sajjadintel** [comment]
@Anton2319  Thanks

**Comment by Anton2319** [comment]
The working prototype is ready, you can test it now. Only supports password authentication for now unfortunately

**Comment by Anton2319** [comment]
Done with the full working prototype
