### ISSUE TITLE
aapt2-windows.jar

### ISSUE THREAD

**Issue by HamedAp** [Anton2319/VPNoverSSH#3]
Hello 
I want to make project and i got this error : 

`Execution failed for task ':app:processDebugResources'.
> Could not isolate parameters com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@2274392c of artifact transform AarResourcesCompilerTransform
   > Could not isolate value com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@2274392c of type AarResourcesCompilerTransform.Parameters
      > Could not resolve all files for configuration ':app:detachedConfiguration2'.
         > Could not find com.android.tools.build:aapt2:8.0.0-9289358.
           Searched in the following locations:
             - https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/8.0.0-9289358/aapt2-8.0.0-9289358.pom
             - https://repo.maven.apache.org/maven2/com/android/tools/build/aapt2/8.0.0-9289358/aapt2-8.0.0-9289358.pom
             - https://jitpack.io/com/android/tools/build/aapt2/8.0.0-9289358/aapt2-8.0.0-9289358.pom
             - file:/D:/Android/VPNoverSSH-main/VPNoverSSH-main/app/libs/aapt2-8.0.0-9289358-windows.jar
             - file:/D:/Android/VPNoverSSH-main/VPNoverSSH-main/app/libs/aapt2-windows.jar
           Required by:
               project :app`
               
               Would you please help me with that ?

**Comment by Anton2319** [comment]
I've never built this project on Windows, so I have no idea what might go wrong. My assumption is that either the google repository in your country is blocked ([see this answer](https://stackoverflow.com/a/59509104/11945017)), in which case you would have to use a proxy or a VPN, or the Android Studio version is outdated. What Windows version and Android Studio version are you using to build it? I would appreciate it if you could figure out what went wrong and report it here, I will update my readme with build instructions for Windows. If nothing helps, I can suggest creating a WSL environment and building this project there via `gradlew build`. 
You can use my build as well if you simply want a working release: https://github.com/Anton2319/VPNoverSSH/releases/tag/v1.0-prerelease

**Comment by HamedAp** [comment]
I Found the problem . its JDK Version .  
Would you please tell me about your JDK version ?
